# This file was generated by GoReleaser. DO NOT EDIT.
cask "wocontrol" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "7c8d38896a45f52d8d326319bb7070230b58c9e88b8e58915df457536fdd527d"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
    on_arm do
      sha256 "d706c3c62c12bc21fa2f9d362b95815815f16f9c8a93a8ad84f980651a6b3ae0"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
  end

  on_linux do
    on_intel do
      sha256 "16fe9311272a4c2cffb1572d3073662b8ef8987f00b24eab1a2cf0f25961b912"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
    on_arm do
      sha256 "9c72cc284a78bd584a577651f8d11d2ffaa07128a909445d41c450be57e39f64"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
  end

  name "wocontrol"
  desc "WO spec crawler and execution pipeline"
  homepage "https://github.com/ppiankov/wocontrol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wocontrol"

  # No zap stanza required

end
