# This file was generated by GoReleaser. DO NOT EDIT.
cask "wocontrol" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "ef7a919354d789fa8d750c59197ee0d26086036cddf7dfcf5c178e5683414bf5"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
    on_arm do
      sha256 "8cd29884c0da28a2738ae3b1cf845c34ad4e8ba1d7e3306970315a3c906aafde"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef8b5abcbb3ab1716eda66d13e8a592d9d5e92a9a04033c3f0c8442c7e05f328"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
    on_arm do
      sha256 "595002de7a2a262c456e6baaaeeefa61e566ff40cbf4940d95d4ea1c45ae47d7"
      url "https://github.com/ppiankov/wocontrol/releases/download/v#{version}/wocontrol_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ppiankov/wocontrol/"
    end
  end

  name "wocontrol"
  desc "WO spec crawler and execution pipeline"
  homepage "https://github.com/ppiankov/wocontrol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wocontrol"

  # No zap stanza required

end
