# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aispectre < Formula
  desc "AI/LLM spend waste auditor"
  homepage "https://github.com/ppiankov/aispectre"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.0/aispectre_0.2.0_darwin_amd64.tar.gz"
      sha256 "b0b3743d464720f42e6541c5fc00a3201826c55110938491701516490c0e94e0"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.0/aispectre_0.2.0_darwin_arm64.tar.gz"
      sha256 "52e9a47a3a26b70253e4379f85562fa1833db9254e2b4f8dd72fababa3abfc8d"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.0/aispectre_0.2.0_linux_amd64.tar.gz"
      sha256 "1b7a2234b7fd82146e151b65145a27c12bd438204b8c995137ef3725f4a0576a"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.0/aispectre_0.2.0_linux_arm64.tar.gz"
      sha256 "b0c760ff67809e9f68d6f9326103dbd5a999973964e85a09d9f4b14eae1fa14a"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  test do
    system "#{bin}/aispectre", "version"
  end
end
