# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aispectre < Formula
  desc "AI/LLM spend waste auditor"
  homepage "https://github.com/ppiankov/aispectre"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.1/aispectre_0.2.1_darwin_amd64.tar.gz"
      sha256 "c88a10192e57a4a0e3d088a0ef5694428407735c244bf94197bfe45137af50a7"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.1/aispectre_0.2.1_darwin_arm64.tar.gz"
      sha256 "719e725949bfaec6e25b864f4cc8d0e6cc19788e4b3fe7194da82ef26f00105a"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.1/aispectre_0.2.1_linux_amd64.tar.gz"
      sha256 "750a9cffa2af851c0d8f535b5651ae4e06ccce27149fe0daae89139ee0184b51"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.2.1/aispectre_0.2.1_linux_arm64.tar.gz"
      sha256 "fbd5ab44755354015b8ac69b5144de9af4bcb8fd1e5a95ad28b968c7799245da"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  test do
    system "#{bin}/aispectre", "version"
  end
end
