# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aispectre < Formula
  desc "AI/LLM spend waste auditor"
  homepage "https://github.com/ppiankov/aispectre"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.1.1/aispectre_0.1.1_darwin_amd64.tar.gz"
      sha256 "8cae3cf6f1fc0a308cc1aef61a8927902108f3023879777effbd30d45b1742a2"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.1.1/aispectre_0.1.1_darwin_arm64.tar.gz"
      sha256 "43d3f4b2e77bf1d6d1f5ccf68eb9e185990f6d37bb8d3405d417ffc2c30d64c3"

      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.1.1/aispectre_0.1.1_linux_amd64.tar.gz"
      sha256 "5b8a6cd68b0c3ecf9c7d71a9461092419aec62f3d20a6a1aee6ec26fb09f0bac"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/aispectre/releases/download/v0.1.1/aispectre_0.1.1_linux_arm64.tar.gz"
      sha256 "8fba29c0e36b8215191c227460d22b541ad85fd313d306615b059644b02501d9"
      define_method(:install) do
        bin.install "aispectre"
      end
    end
  end

  test do
    system "#{bin}/aispectre", "version"
  end
end
