# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ancc < Formula
  desc "Static validator for the Agent-Native CLI Convention"
  homepage "https://github.com/ppiankov/ancc"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/ancc/releases/download/v0.2.2/ancc-0.2.2-darwin-amd64.tar.gz"
      sha256 "06ef977fae07bc0f2d575e1e290609b0bded15fe5962d2f44c91c5898c9476df"

      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/ancc/releases/download/v0.2.2/ancc-0.2.2-darwin-arm64.tar.gz"
      sha256 "e223c2f8e697d2829809f27db0f58824405c1a88edd4e40bcd7acdb9091edeb7"

      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.2.2/ancc-0.2.2-linux-amd64.tar.gz"
      sha256 "d5316e98e859a6d92a40fd56bf098e56e20043564684104bc26921774ba7e4da"
      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.2.2/ancc-0.2.2-linux-arm64.tar.gz"
      sha256 "86f51055b06da38547a624028d544a9fb44817bb6c23e927799f72a82de09dae"
      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  test do
    system "#{bin}/ancc", "--version"
  end
end
