# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ancc < Formula
  desc "Static validator for the Agent-Native CLI Convention"
  homepage "https://github.com/ppiankov/ancc"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/ancc/releases/download/v0.7.0/ancc-0.7.0-darwin-amd64.tar.gz"
      sha256 "ce94fcaebc6f5070b63ed9c563527b49de95885bb3dc0e38f77feb1d4a3a7568"

      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/ancc/releases/download/v0.7.0/ancc-0.7.0-darwin-arm64.tar.gz"
      sha256 "878cb9290d38d105301981266c555d76cfd49188d509fa88680c2c8524e1407e"

      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.7.0/ancc-0.7.0-linux-amd64.tar.gz"
      sha256 "69784477c9a914f9ec84c087e2c6052658e3a2a68c624b5fb4d5d22de62f0a99"
      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.7.0/ancc-0.7.0-linux-arm64.tar.gz"
      sha256 "d9488ba42deecd346686de294460dfdedca3beee1e8feb5f773936b4d0f57aa1"
      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  test do
    system "#{bin}/ancc", "--version"
  end
end
