# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ancc < Formula
  desc "Static validator for the Agent-Native CLI Convention"
  homepage "https://github.com/ppiankov/ancc"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/ancc/releases/download/v0.4.0/ancc-0.4.0-darwin-amd64.tar.gz"
      sha256 "460fb8424e838a5999da3226cda76d98c450d780bd05210b3465bef10f1edea1"

      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/ancc/releases/download/v0.4.0/ancc-0.4.0-darwin-arm64.tar.gz"
      sha256 "45345bcd65ae9e7d8279851c3e5737d9bc9d749ba1df0fee5e1046dde442d133"

      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.4.0/ancc-0.4.0-linux-amd64.tar.gz"
      sha256 "9d16e154ac9023de0169e89aab13d4dc31da2f621238d1f7cea1f2bfdff2b220"
      define_method(:install) do
        bin.install "ancc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ancc/releases/download/v0.4.0/ancc-0.4.0-linux-arm64.tar.gz"
      sha256 "05b46bc4ceabafbf62a0da668cc71009f52cdc8131d0a68d1cd13304f334a304"
      define_method(:install) do
        bin.install "ancc"
      end
    end
  end

  test do
    system "#{bin}/ancc", "--version"
  end
end
