# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsspectre < Formula
  desc "AWS resource waste auditor — finds idle, orphaned, and oversized resources"
  homepage "https://github.com/ppiankov/awsspectre"
  version "0.8.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/awsspectre/releases/download/v0.8.6/awsspectre_0.8.6_darwin_amd64.tar.gz"
      sha256 "ad26fc58119b7b16a76c138b58d37ee63dcded7ca26a99cff71349f1ad5eb7e3"

      define_method(:install) do
        bin.install "awsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/awsspectre/releases/download/v0.8.6/awsspectre_0.8.6_darwin_arm64.tar.gz"
      sha256 "42dc1bd28f3a00ad0e778e46d596a880dd3c16c1b13fd409726d7d433ddc7bf1"

      define_method(:install) do
        bin.install "awsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/awsspectre/releases/download/v0.8.6/awsspectre_0.8.6_linux_amd64.tar.gz"
      sha256 "133d82fba795f523fd74c0e449c17f7132e79fb7a9259bfced481f357de2ef46"
      define_method(:install) do
        bin.install "awsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/awsspectre/releases/download/v0.8.6/awsspectre_0.8.6_linux_arm64.tar.gz"
      sha256 "4793bd23f0067d183983afac1b4fbaa69e7e7cdb19388eed84aabdba3d7d65c1"
      define_method(:install) do
        bin.install "awsspectre"
      end
    end
  end

  test do
    system "#{bin}/awsspectre", "version"
  end
end
