# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azurespectre < Formula
  desc "Azure resource waste auditor"
  homepage "https://github.com/ppiankov/azurespectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1355e3be9906c16f3846db53ed13c3071a69b44456a575b569fa23746d319d8"

      define_method(:install) do
        bin.install "azurespectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "8b9ce214954bc5a3e02eca8f04312cedf319e44f181ae23e1daf7ade0353618c"

      define_method(:install) do
        bin.install "azurespectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_linux_amd64.tar.gz"
      sha256 "58edac81df1ebee5b0ca2f0ad1bcb50b9f10828f3e1fcf75d24fc28732811ce6"
      define_method(:install) do
        bin.install "azurespectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_linux_arm64.tar.gz"
      sha256 "ce5f77e17732c0cd77b7f7cfecf142067af5a3852570c76a7d10a77d4c11bd8d"
      define_method(:install) do
        bin.install "azurespectre"
      end
    end
  end

  test do
    system "#{bin}/azurespectre", "version"
  end
end
