# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azurespectre < Formula
  desc "Azure resource waste auditor"
  homepage "https://github.com/ppiankov/azurespectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "a0ffa00a7dab68eed1a9223ac894aea6356f2331c2c007ac313b54d89fcbf595"

      define_method(:install) do
        bin.install "azurespectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "7681181887f1c7beea220574e988e3c072514eb2b8e636b4b01953542bba6e50"

      define_method(:install) do
        bin.install "azurespectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_linux_amd64.tar.gz"
      sha256 "1eb114c85829b530761581cb5aac4e8e6e59e5d7d33c18cc9e44d2bdb8ff4a8a"
      define_method(:install) do
        bin.install "azurespectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/azurespectre/releases/download/v0.1.0/azurespectre_0.1.0_linux_arm64.tar.gz"
      sha256 "b846d9fbe707d8b9e2cacd946b3d9e5e30755264ce76572089414fbe01a97576"
      define_method(:install) do
        bin.install "azurespectre"
      end
    end
  end

  test do
    system "#{bin}/azurespectre", "version"
  end
end
