# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cispectre < Formula
  desc "GitHub Actions waste auditor"
  homepage "https://github.com/ppiankov/cispectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/cispectre/releases/download/v0.1.0/cispectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "3c915ca5f4bc8f660e642ba2084a3eda1e2e0b2e139605afd02415165978ee25"

      define_method(:install) do
        bin.install "cispectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/cispectre/releases/download/v0.1.0/cispectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "443e0761cc0b934df7cac622e22945af99a5ce62c352a698e22e09fa8092e333"

      define_method(:install) do
        bin.install "cispectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/cispectre/releases/download/v0.1.0/cispectre_0.1.0_linux_amd64.tar.gz"
      sha256 "6eaf4c1ac556ed34dbba519673517f55378c662e2e96d4ac0508a2becd37beea"
      define_method(:install) do
        bin.install "cispectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/cispectre/releases/download/v0.1.0/cispectre_0.1.0_linux_arm64.tar.gz"
      sha256 "4e79630895a6901455d8272fdb4c3f136342233c10d885959be72b171284bdbe"
      define_method(:install) do
        bin.install "cispectre"
      end
    end
  end

  test do
    system "#{bin}/cispectre", "version"
  end
end
