# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clickspectre < Formula
  desc "ClickHouse usage analyzer — identifies unused tables, service dependencies, and cleanup recommendations"
  homepage "https://github.com/ppiankov/clickspectre"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.1.0/clickspectre_1.1.0_darwin_amd64.tar.gz"
      sha256 "35a8dcda176176e92fde589791b64e9a7bf27bd6ac8cbd8663a4b5e6022f8177"

      define_method(:install) do
        bin.install "clickspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.1.0/clickspectre_1.1.0_darwin_arm64.tar.gz"
      sha256 "8fe750612ce90e5a4250c6043b2f8b8e60d9cf31731de8f12eecc094b09c9dd1"

      define_method(:install) do
        bin.install "clickspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.1.0/clickspectre_1.1.0_linux_amd64.tar.gz"
      sha256 "0d95e34f65f898bc51f9c0291b1574d2aaaacdec174dc560c28315a0e1aa8855"
      define_method(:install) do
        bin.install "clickspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.1.0/clickspectre_1.1.0_linux_arm64.tar.gz"
      sha256 "6cdda1602c213da2bc68ce1a636a17b4e985353ef92791155a820a3bdb7ed477"
      define_method(:install) do
        bin.install "clickspectre"
      end
    end
  end

  test do
    assert_match "clickspectre", shell_output("#{bin}/clickspectre version")
  end
end
