# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clickspectre < Formula
  desc "ClickHouse usage analyzer — identifies unused tables, service dependencies, and cleanup recommendations"
  homepage "https://github.com/ppiankov/clickspectre"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.0.2/clickspectre_1.0.2_darwin_amd64.tar.gz"
      sha256 "7c82139faf313657624e38db78a8faa04d3d849a35d834d5f895a9085b627b25"

      define_method(:install) do
        bin.install "clickspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.0.2/clickspectre_1.0.2_darwin_arm64.tar.gz"
      sha256 "e558586d73c84a3f59377a6340c2c40ff361b473ae628213b177eb5655b09d13"

      define_method(:install) do
        bin.install "clickspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.0.2/clickspectre_1.0.2_linux_amd64.tar.gz"
      sha256 "395af927db8665e599c77d4d29e2d0827550cdf08ef0c5ce8aae36e8236474c6"
      define_method(:install) do
        bin.install "clickspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/clickspectre/releases/download/v1.0.2/clickspectre_1.0.2_linux_arm64.tar.gz"
      sha256 "e14c98096fe152fd5eed55259fdae8edfdecfcc6efc692af796ced12f048752c"
      define_method(:install) do
        bin.install "clickspectre"
      end
    end
  end

  test do
    assert_match "clickspectre", shell_output("#{bin}/clickspectre version")
  end
end
