# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contextspectre < Formula
  desc "Claude Code conversation context manager"
  homepage "https://github.com/ppiankov/contextspectre"
  version "0.33.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.33.1/contextspectre_0.33.1_darwin_amd64.tar.gz"
      sha256 "7f0b50c55122d86328532d730a9ed0ef8b1a51dfca03dd2968c0f4f0949e5581"

      define_method(:install) do
        bin.install "contextspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.33.1/contextspectre_0.33.1_darwin_arm64.tar.gz"
      sha256 "4ca52a833cf131fa3aad86f874427603057be22340260b2995dc368ebbee3557"

      define_method(:install) do
        bin.install "contextspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.33.1/contextspectre_0.33.1_linux_amd64.tar.gz"
      sha256 "4a5d85b92fb40d696390fb69715085e280460f07bf266236a52c879c40d1dd57"
      define_method(:install) do
        bin.install "contextspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.33.1/contextspectre_0.33.1_linux_arm64.tar.gz"
      sha256 "31ee2f85109077959b2ba501a87a66ba464d1caafbacf057131175e41eaf6cb6"
      define_method(:install) do
        bin.install "contextspectre"
      end
    end
  end

  test do
    system "#{bin}/contextspectre", "version"
  end
end
