# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contextspectre < Formula
  desc "Claude Code conversation context manager"
  homepage "https://github.com/ppiankov/contextspectre"
  version "0.44.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.44.1/contextspectre_0.44.1_darwin_amd64.tar.gz"
      sha256 "b9df8ccae336471de461d34943acc2cc8598fa9bea7e6694352fcbab3354bbfd"

      define_method(:install) do
        bin.install "contextspectre"
        bin.install_symlink "contextspectre" => "cs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.44.1/contextspectre_0.44.1_darwin_arm64.tar.gz"
      sha256 "2024a2bbe562ddb1a83fcd5bf7cf0cf0b5943373f3775662a875349e1f30f63d"

      define_method(:install) do
        bin.install "contextspectre"
        bin.install_symlink "contextspectre" => "cs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.44.1/contextspectre_0.44.1_linux_amd64.tar.gz"
      sha256 "dc2abf53c94fa680ac0b8764a641ba82da293c426e6aa36bee50682672e739b5"
      define_method(:install) do
        bin.install "contextspectre"
        bin.install_symlink "contextspectre" => "cs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/contextspectre/releases/download/v0.44.1/contextspectre_0.44.1_linux_arm64.tar.gz"
      sha256 "bce0822fb2907585793500a977ada9c03390f88bf26cf813a8bf72bb3056a57b"
      define_method(:install) do
        bin.install "contextspectre"
        bin.install_symlink "contextspectre" => "cs"
      end
    end
  end

  test do
    system "#{bin}/contextspectre", "version"
  end
end
