# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsspectre < Formula
  desc "DNS hygiene and subdomain takeover detection"
  homepage "https://github.com/ppiankov/dnsspectre"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.1/dnsspectre_0.3.1_darwin_amd64.tar.gz"
      sha256 "67a0b1c9874910633e1d2bb21ff99978b55e72ff10d0ccb099803cb483f71b99"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.1/dnsspectre_0.3.1_darwin_arm64.tar.gz"
      sha256 "91e5c59b794476a482578ffc3a51d14acc35ab88d45fa80a1e0ae3b30d5c8196"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.1/dnsspectre_0.3.1_linux_amd64.tar.gz"
      sha256 "ce19e2ffaf6135f9e4dc4294f08af990b322f48ad2d449565551d2c934a5b344"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.1/dnsspectre_0.3.1_linux_arm64.tar.gz"
      sha256 "06ca37c77eb9673a746fc282607b16fd2ba0e39cb40424a843a86af32d0e75a4"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  test do
    system "#{bin}/dnsspectre", "version"
  end
end
