# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsspectre < Formula
  desc "DNS hygiene and subdomain takeover detection"
  homepage "https://github.com/ppiankov/dnsspectre"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.0/dnsspectre_0.3.0_darwin_amd64.tar.gz"
      sha256 "8bd7ce32b1a60291c3cd427e014d63614b327dbaea4039f66deabe620dd03b3f"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.0/dnsspectre_0.3.0_darwin_arm64.tar.gz"
      sha256 "81890cc886e0b7ec2bd0a69be4956feec8acec7781ebb64a8a52ebd259c4c025"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.0/dnsspectre_0.3.0_linux_amd64.tar.gz"
      sha256 "7ef425f9d7914a5c629214bcec05aea7fb238f213a7fb30da7361d81b5935adb"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.3.0/dnsspectre_0.3.0_linux_arm64.tar.gz"
      sha256 "30280b3887d06d3ff20fed7b495be344c38417f9a6d0be06214f1e3268c1c143"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  test do
    system "#{bin}/dnsspectre", "version"
  end
end
