# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsspectre < Formula
  desc "DNS hygiene and subdomain takeover detection"
  homepage "https://github.com/ppiankov/dnsspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.1.0/dnsspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "c0d86b19f40139895af75bb181c4cb9e05cd7c04ffbc4eb7de4b80c78f086300"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.1.0/dnsspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "af05373f8a50cc792cd385e5a5cb62765ed5036dfe99639e3b5d9a8f097773dc"

      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.1.0/dnsspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "3a696366453b77b4a290af93c8e4d793370530c00c32c0ef78656d2ea09fb6c9"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/dnsspectre/releases/download/v0.1.0/dnsspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "7f9fd2b4ae7eb23346fa93b61533c172e3165c976cfb4dd4a6d3ad2d630b2af1"
      define_method(:install) do
        bin.install "dnsspectre"
      end
    end
  end

  test do
    system "#{bin}/dnsspectre", "version"
  end
end
