# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecrspectre < Formula
  desc "Container registry waste auditor — finds stale, untagged, and oversized images in AWS ECR and GCP Artifact Registry"
  homepage "https://github.com/ppiankov/ecrspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/ecrspectre/releases/download/v0.1.0/ecrspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "33d15d00c642e330d70544133e3cd0ea06c1a1d3803dff2c75515ae2c649cfa2"

      define_method(:install) do
        bin.install "ecrspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/ecrspectre/releases/download/v0.1.0/ecrspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "c8ec1eb6905490e43813d479aa6cfcae2aaaaef619e1dd8526870b25f8ed412c"

      define_method(:install) do
        bin.install "ecrspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ecrspectre/releases/download/v0.1.0/ecrspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "d00049b0074f8e969d2c684fe9680262fae6c9a0b01aa79c19e22db334be047a"
      define_method(:install) do
        bin.install "ecrspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/ecrspectre/releases/download/v0.1.0/ecrspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "a7456842cef09003e547d491eee44540e886cb14d695d40552d73854cf6789e1"
      define_method(:install) do
        bin.install "ecrspectre"
      end
    end
  end

  test do
    system "#{bin}/ecrspectre", "version"
  end
end
