# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elasticspectre < Formula
  desc "Elasticsearch/OpenSearch waste auditor"
  homepage "https://github.com/ppiankov/elasticspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/elasticspectre/releases/download/v0.1.0/elasticspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "55cc077e9cea318a7552988b0b0df5d4f751f1aba16d6dd5c811471273abc1f2"

      define_method(:install) do
        bin.install "elasticspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/elasticspectre/releases/download/v0.1.0/elasticspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "3e5a8750cf9371f004d97ba14e37878e0659b0f5a72ce0cb26c69df456464d03"

      define_method(:install) do
        bin.install "elasticspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/elasticspectre/releases/download/v0.1.0/elasticspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "5d7449feeb9a1af495594845ff4ee199a567def2962d50077a84e191eef01b74"
      define_method(:install) do
        bin.install "elasticspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/elasticspectre/releases/download/v0.1.0/elasticspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "5469312a4b22d6b97e7760e332f45b3490eb50a88e03cb9acad6fa5f4cfe8e14"
      define_method(:install) do
        bin.install "elasticspectre"
      end
    end
  end

  test do
    system "#{bin}/elasticspectre", "version"
  end
end
