# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freeflow < Formula
  desc "CLI intelligence layer for Freeflow task-tracker"
  homepage "https://github.com/ppiankov/freeflow-dist"
  version "0.13.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.18/freeflow_darwin_amd64.tar.gz"
      sha256 "c05fc3a3068ebc954a5b1bfe566eef31b3b689e9969ab5a50f0736beb02e999c"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.18/freeflow_darwin_arm64.tar.gz"
      sha256 "2a74ed5c0a4a1f1c6aa55a2861817ab024812931d2c3c6364f3b5afecb877e79"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.18/freeflow_linux_amd64.tar.gz"
      sha256 "f7d3c8cc9a36cfc168e57cd2df726bfe7ee22f5b68eabc716d5a25eeae245000"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.18/freeflow_linux_arm64.tar.gz"
      sha256 "4abaa72f0950355c0ff3e8e51807995fd550f501e40f0e68b70d75deb5461cbd"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  def caveats
    <<~EOS
      The Freeflow agent skill is installed with the CLI.

      Locate it with:
        freeflow skill path

      Print it with:
        freeflow skill print
    EOS
  end

  test do
    system "#{bin}/freeflow", "version"
  end
end
