# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freeflow < Formula
  desc "CLI intelligence layer for Freeflow task-tracker"
  homepage "https://github.com/ppiankov/freeflow-dist"
  version "0.13.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.16/freeflow_darwin_amd64.tar.gz"
      sha256 "2092fbd5adb2a729c801276863b53f7a3ef273925541337c9c3293ca5d220a49"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.16/freeflow_darwin_arm64.tar.gz"
      sha256 "f38e552d74db6346a912ffeb70d46da8e461400bee17962dc25c2775d486636d"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.16/freeflow_linux_amd64.tar.gz"
      sha256 "ec105a5ce8d121ac17a1384b3cd8b2e02e4a3507aa1e02e45cff87ee90b0a8c2"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.13.16/freeflow_linux_arm64.tar.gz"
      sha256 "fd5b94d05bd7143abb8b15f35d0ec76c2f1d25c0bb9c51c5a4972b81c77e7858"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  def caveats
    <<~EOS
      The Freeflow agent skill is installed with the CLI.

      Locate it with:
        freeflow skill path

      Print it with:
        freeflow skill print
    EOS
  end

  test do
    system "#{bin}/freeflow", "version"
  end
end
