# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freeflow < Formula
  desc "CLI intelligence layer for Freeflow task-tracker"
  homepage "https://github.com/ppiankov/freeflow-dist"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.3.2/freeflow_darwin_amd64.tar.gz"
      sha256 "c79c19c623dc1a3b9902b2db6e2746725686c02708793ca852a9f70dce12196e"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.3.2/freeflow_darwin_arm64.tar.gz"
      sha256 "410a5a209f5a95443ae8a318dbc430608249df3ef996e957164d615c3451bd7a"

      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.3.2/freeflow_linux_amd64.tar.gz"
      sha256 "ca2ef0decaf8ef9872be23d57358f87624a63e8b886fcd347dbaac35958d7584"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/freeflow-dist/releases/download/v0.3.2/freeflow_linux_arm64.tar.gz"
      sha256 "016e20e2ac9616d8674926edfdbb44c1c5eb0d38c4768945e08d29fc92601fcb"
      define_method(:install) do
        bin.install "freeflow"
        # WO-146: install SKILL.md once (Homebrew .install MOVES the file); symlink
        # the doc copy so a second .install does not ENOENT on the consumed source.
        pkgshare.install "SKILL.md"
        doc.install_symlink pkgshare/"SKILL.md" => "SKILL.md"
      end
    end
  end

  def caveats
    <<~EOS
      The Freeflow agent skill is installed with the CLI.

      Locate it with:
        freeflow skill path

      Print it with:
        freeflow skill print
    EOS
  end

  test do
    system "#{bin}/freeflow", "version"
  end
end
