# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcpspectre < Formula
  desc "GCP resource waste auditor — finds idle, orphaned, and oversized resources"
  homepage "https://github.com/ppiankov/gcpspectre"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.2.0/gcpspectre_0.2.0_darwin_amd64.tar.gz"
      sha256 "47da1aee81bd32c61bfc131f866f17c9d3c1937e842fd6e59fbef4f4d2856af2"

      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.2.0/gcpspectre_0.2.0_darwin_arm64.tar.gz"
      sha256 "4f25efed7e4f863d8b481f3ef659e33b5ff55cdba6ee7d5944bca1334a37da94"

      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.2.0/gcpspectre_0.2.0_linux_amd64.tar.gz"
      sha256 "4d3076922b1eb3a5b313c4e77807e6045022c70b8d4b1d4724f2fa48243f60bd"
      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.2.0/gcpspectre_0.2.0_linux_arm64.tar.gz"
      sha256 "50c0f16792bbbb95ea1e1f61da0d395a3360f1414808b4664c5f680349726793"
      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
  end

  test do
    system "#{bin}/gcpspectre", "version"
  end
end
