# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcpspectre < Formula
  desc "GCP resource waste auditor — finds idle, orphaned, and oversized resources"
  homepage "https://github.com/ppiankov/gcpspectre"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.1.1/gcpspectre_0.1.1_darwin_amd64.tar.gz"
      sha256 "12ddd37370b764fc7b92bb102b998923e3a16cb9bd44c591936c6014fff77ba5"

      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.1.1/gcpspectre_0.1.1_darwin_arm64.tar.gz"
      sha256 "5e2ba133a6089d8efe8ba40d625f360cc4fd86ee4633eb2a4f2c81cf97d542c8"

      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.1.1/gcpspectre_0.1.1_linux_amd64.tar.gz"
      sha256 "198c9cb607c425aed2263bfed2f500d8d3b09f4a9300c5125ac6f720ffb9454b"
      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcpspectre/releases/download/v0.1.1/gcpspectre_0.1.1_linux_arm64.tar.gz"
      sha256 "c272c3d70996ae4145df95fa1f3a12e9a3aaefb64ce95bc2942d34a0cd580d4f"
      define_method(:install) do
        bin.install "gcpspectre"
      end
    end
  end

  test do
    system "#{bin}/gcpspectre", "version"
  end
end
