# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcsspectre < Formula
  desc "GCP Cloud Storage auditor — finds unused, misconfigured, and wasteful GCS buckets"
  homepage "https://github.com/ppiankov/gcsspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/gcsspectre/releases/download/v0.1.0/gcsspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "18b2dac523f12d0b5452f0369eb2a4e38fcd8be2cee82f4330e56442f0313969"

      define_method(:install) do
        bin.install "gcsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/gcsspectre/releases/download/v0.1.0/gcsspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "34e065b1e3e82143fa72c765175cb6a7b36fd2e977531ed1252884f59505c1da"

      define_method(:install) do
        bin.install "gcsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcsspectre/releases/download/v0.1.0/gcsspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "15632f13dfc1e30384a4f654fba6d776ea1334d811ca6011bd159a135976d98c"
      define_method(:install) do
        bin.install "gcsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/gcsspectre/releases/download/v0.1.0/gcsspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "4469e969647722384d063091884853a5e50981c89b5bae31a098d655b04d9cef"
      define_method(:install) do
        bin.install "gcsspectre"
      end
    end
  end

  test do
    system "#{bin}/gcsspectre", "version"
  end
end
