# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iamspectre < Formula
  desc "Cross-cloud IAM auditor — finds unused, over-permissioned, and stale identities"
  homepage "https://github.com/ppiankov/iamspectre"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.3.0/iamspectre_0.3.0_darwin_amd64.tar.gz"
      sha256 "258e49d002344793ba5805abcefd144e2f97058651ad96f7f2f3b13f705da66e"

      define_method(:install) do
        bin.install "iamspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.3.0/iamspectre_0.3.0_darwin_arm64.tar.gz"
      sha256 "e64a114c4286da56ac3f8c33344e8977c31008685e3a75b3d11d7056fead2a8c"

      define_method(:install) do
        bin.install "iamspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.3.0/iamspectre_0.3.0_linux_amd64.tar.gz"
      sha256 "5fd338a69a9a0f0320cb264cb2730974244b0da42e8724e363325f9c7b035450"
      define_method(:install) do
        bin.install "iamspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.3.0/iamspectre_0.3.0_linux_arm64.tar.gz"
      sha256 "40dc743569694bf39cfde248b2f55244fbc69187eb691c5df27fbb95c333a287"
      define_method(:install) do
        bin.install "iamspectre"
      end
    end
  end

  test do
    system "#{bin}/iamspectre", "version"
  end
end
