# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iamspectre < Formula
  desc "Cross-cloud IAM auditor — finds unused, over-permissioned, and stale identities"
  homepage "https://github.com/ppiankov/iamspectre"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.6.0/iamspectre_0.6.0_darwin_amd64.tar.gz"
      sha256 "2808a6766c4b1d21fe549674a3c64abb7e70c0564dbb681ea4b86133b9dd9f17"

      def install
        bin.install "iamspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.6.0/iamspectre_0.6.0_darwin_arm64.tar.gz"
      sha256 "e8225a4e045bb7acb2214144858fbcad571559b0f0bcc7eda390d412c39abeea"

      def install
        bin.install "iamspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.6.0/iamspectre_0.6.0_linux_amd64.tar.gz"
      sha256 "ca881f9972143bac2134a8111114b283634287ec31b1101bcf9b911057c6d437"
      def install
        bin.install "iamspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/iamspectre/releases/download/v0.6.0/iamspectre_0.6.0_linux_arm64.tar.gz"
      sha256 "d780b1b2855ea1242f287124316b6b7543eab26786d13ed672a724f768c2446a"
      def install
        bin.install "iamspectre"
      end
    end
  end

  test do
    system "#{bin}/iamspectre", "version"
  end
end
