# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infranow < Formula
  desc "Real-time infrastructure triage — deterministic problem detection for Kubernetes and Prometheus"
  homepage "https://github.com/ppiankov/infranow"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/infranow/releases/download/v0.3.1/infranow_0.3.1_darwin_amd64.tar.gz"
      sha256 "6bfbd0f242292f457e431af90c4a99c079aae26ae49eb50b3b909f57181b51b7"

      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/infranow/releases/download/v0.3.1/infranow_0.3.1_darwin_arm64.tar.gz"
      sha256 "7b98d930f921e0ce382865fbf2b75ff1360bdecc9443b56d59ab16c838bedcf1"

      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.3.1/infranow_0.3.1_linux_amd64.tar.gz"
      sha256 "636b8dd70f22404a21737ba3d19a40bbb008e2234bcc0c6b0c1db2135d39d1fc"
      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.3.1/infranow_0.3.1_linux_arm64.tar.gz"
      sha256 "0fd1ea68f1e9cf3d78d607db6e54d1828c77acd90b14165050d19a1caa5dd63f"
      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  test do
    system "#{bin}/infranow", "version"
  end
end
