# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infranow < Formula
  desc "Real-time infrastructure triage — deterministic problem detection for Kubernetes and Prometheus"
  homepage "https://github.com/ppiankov/infranow"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/infranow/releases/download/v0.5.0/infranow_0.5.0_darwin_amd64.tar.gz"
      sha256 "b316ce3c861ec7a6c50c32c7cffad7860bba99fd1b022188f4a3f1dd6ea3af7d"

      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/infranow/releases/download/v0.5.0/infranow_0.5.0_darwin_arm64.tar.gz"
      sha256 "b2587366afb5d56f0dc50c9eadf23801d4627c477c10884c0d15425efca6ca0a"

      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.5.0/infranow_0.5.0_linux_amd64.tar.gz"
      sha256 "79aae0c2010e9902fac29914fdbf0ca73931e63eb47b2facf32ed06145e88a1a"
      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.5.0/infranow_0.5.0_linux_arm64.tar.gz"
      sha256 "1cf173ad455c27bf7b1048ddad712d42477c9844c39116b9c69c1296afd98393"
      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  test do
    system "#{bin}/infranow", "version"
  end
end
