# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infranow < Formula
  desc "Real-time infrastructure triage — deterministic problem detection for Kubernetes and Prometheus"
  homepage "https://github.com/ppiankov/infranow"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/infranow/releases/download/v0.2.0/infranow_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ba6058b12d53df0dac1fa6174b7019097d8c6bb685a88b5778208129a7330f6"

      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/infranow/releases/download/v0.2.0/infranow_0.2.0_darwin_arm64.tar.gz"
      sha256 "0467a9f9e6c5093b1c90ae437d219522bf0f9851d52e507c2edd29fa9cc89228"

      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.2.0/infranow_0.2.0_linux_amd64.tar.gz"
      sha256 "871ed0e72a54de671cfa67dbbd6be17e8390ccd707c027a2d4c65b3996a42c9b"
      define_method(:install) do
        bin.install "infranow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/infranow/releases/download/v0.2.0/infranow_0.2.0_linux_arm64.tar.gz"
      sha256 "a234b80c7540a42f2195154552377a5801aac1b2d197721240370ef61fc770a3"
      define_method(:install) do
        bin.install "infranow"
      end
    end
  end

  test do
    system "#{bin}/infranow", "version"
  end
end
