# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkaspectre < Formula
  desc "Kafka cluster auditor — identifies unused, orphaned, and misconfigured topics"
  homepage "https://github.com/ppiankov/kafkaspectre"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.3/kafkaspectre_0.2.3_darwin_amd64.tar.gz"
      sha256 "5531f062356253bd5d34b6ee4c9da9ce771f2d794308b7709c5207d1b22cf6f3"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.3/kafkaspectre_0.2.3_darwin_arm64.tar.gz"
      sha256 "27b5d9d70888744d74e890d34592a7163f4ea90ef3b0fc8e6e2c9e9a439e37c6"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.3/kafkaspectre_0.2.3_linux_amd64.tar.gz"
      sha256 "ff2e0e9180a2711b7c71fb3a474556a8b19f15713ee7f8779932a377fbfe8f05"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.3/kafkaspectre_0.2.3_linux_arm64.tar.gz"
      sha256 "a08c735c4296e6b5ffe7b3b2b96e418b265099c32c1130b951ae34d690e0cf46"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  test do
    assert_match "kafkaspectre", shell_output("#{bin}/kafkaspectre version")
  end
end
