# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkaspectre < Formula
  desc "Kafka cluster auditor — identifies unused, orphaned, and misconfigured topics"
  homepage "https://github.com/ppiankov/kafkaspectre"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.2/kafkaspectre_0.2.2_darwin_amd64.tar.gz"
      sha256 "b7ec673165fd6d807625a81858786386687256e7474f54691aef49e2f23283d2"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.2/kafkaspectre_0.2.2_darwin_arm64.tar.gz"
      sha256 "9047c4b5ac4d9f06f90c6c6b3442bf906c4a1779cb28b1119b05c726eb73238e"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.2/kafkaspectre_0.2.2_linux_amd64.tar.gz"
      sha256 "0aabe73a2b4d53fa08a4cfe67c1654746ab823f612728d0879625daf094c425d"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.2/kafkaspectre_0.2.2_linux_arm64.tar.gz"
      sha256 "c039a3047ceaa26ddada2b4a94bd5102906acc5a74a5d947466fcc5d9d6890ff"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  test do
    assert_match "kafkaspectre", shell_output("#{bin}/kafkaspectre version")
  end
end
