# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkaspectre < Formula
  desc "Kafka cluster auditor — identifies unused, orphaned, and misconfigured topics"
  homepage "https://github.com/ppiankov/kafkaspectre"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.4/kafkaspectre_0.2.4_darwin_amd64.tar.gz"
      sha256 "073f6b701403fb69f202c2920791660532b5871b7ea0c278544bc39c37e7354d"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.4/kafkaspectre_0.2.4_darwin_arm64.tar.gz"
      sha256 "840a6c219aa3b37e1e40d80bcf4f5c7bee53d9a8996c8aa6d4fc47dc08de80dd"

      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.4/kafkaspectre_0.2.4_linux_amd64.tar.gz"
      sha256 "ab1fae655f5d476e0c1146f9a148290e67a46e31be73c637a7f568b614095494"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kafkaspectre/releases/download/v0.2.4/kafkaspectre_0.2.4_linux_arm64.tar.gz"
      sha256 "c49aa39607bbb51e6a231fd988766c936853853af0b39968870c9b73b8cfe69c"
      define_method(:install) do
        bin.install "kafkaspectre"
      end
    end
  end

  test do
    assert_match "kafkaspectre", shell_output("#{bin}/kafkaspectre version")
  end
end
