# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubespectre < Formula
  desc "Kubernetes security posture auditor"
  homepage "https://github.com/ppiankov/kubespectre"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.2/kubespectre_0.6.2_darwin_amd64.tar.gz"
      sha256 "af09e2a15a21d3b9e3f3c22755837e901a464e31505509b2c84bb8c004c8a3a5"

      define_method(:install) do
        bin.install "kubespectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.2/kubespectre_0.6.2_darwin_arm64.tar.gz"
      sha256 "976c04c401a7e383cf2e5dddcb779e668ca3788a7c0389e5e4d8881013746137"

      define_method(:install) do
        bin.install "kubespectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.2/kubespectre_0.6.2_linux_amd64.tar.gz"
      sha256 "cb18b7250832bb0c4ad78c8ef71e50f2107dcbcee39689fb9c6430db0be607fb"
      define_method(:install) do
        bin.install "kubespectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.2/kubespectre_0.6.2_linux_arm64.tar.gz"
      sha256 "41a6b5e836affe4e7d0ece1bb9fbc8a3e60bd6db4dbfcf5d0911392834fc838d"
      define_method(:install) do
        bin.install "kubespectre"
      end
    end
  end

  test do
    system "#{bin}/kubespectre", "version"
  end
end
