# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubenow < Formula
  desc "Kubernetes resource analysis and cost optimization — deterministic analysis, policy-gated apply, real-time monitoring"
  homepage "https://github.com/ppiankov/kubenow"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kubenow/releases/download/v0.5.0/kubenow_0.5.0_darwin_amd64.tar.gz"
      sha256 "97ab5fbb86adcf70ae37c40d3549956e09f7a55e73d227baf5f97cebb2280f9d"

      define_method(:install) do
        bin.install "kubenow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kubenow/releases/download/v0.5.0/kubenow_0.5.0_darwin_arm64.tar.gz"
      sha256 "5d89d0a65158db38d41c4245da81fabcc19785571b2da2030ce4648e40f6ecf1"

      define_method(:install) do
        bin.install "kubenow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubenow/releases/download/v0.5.0/kubenow_0.5.0_linux_amd64.tar.gz"
      sha256 "97bddcee290e5192627ba148a5444520f2d3ad605a8483800a8ba621a73e5c88"
      define_method(:install) do
        bin.install "kubenow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubenow/releases/download/v0.5.0/kubenow_0.5.0_linux_arm64.tar.gz"
      sha256 "c196b00d110f7f638189dbda6a5ed9c3a32b4735a7270c4c1072d608040d9ee2"
      define_method(:install) do
        bin.install "kubenow"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kubenow version")
  end
end
