# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubespectre < Formula
  desc "Kubernetes security posture auditor"
  homepage "https://github.com/ppiankov/kubespectre"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.1/kubespectre_0.6.1_darwin_amd64.tar.gz"
      sha256 "811f00673a21575867695e9637e52bde7779161d01306724ff9413241572afe3"

      define_method(:install) do
        bin.install "kubespectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.1/kubespectre_0.6.1_darwin_arm64.tar.gz"
      sha256 "0de36c2199f4e7a86f4f850fa7a38b4cc0cb307dc17cae11b223771fa8754166"

      define_method(:install) do
        bin.install "kubespectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.1/kubespectre_0.6.1_linux_amd64.tar.gz"
      sha256 "a4db3797f36fbffeeba9653d09086934994753001d9f2be7f781df85c0f8e44e"
      define_method(:install) do
        bin.install "kubespectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/kubespectre/releases/download/v0.6.1/kubespectre_0.6.1_linux_arm64.tar.gz"
      sha256 "b96b18ba981235fda25e427d4cc0968338971180b19f5edf9a0701d6ee287018"
      define_method(:install) do
        bin.install "kubespectre"
      end
    end
  end

  test do
    system "#{bin}/kubespectre", "version"
  end
end
