# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logspectre < Formula
  desc "Cloud log storage waste auditor"
  homepage "https://github.com/ppiankov/logspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/logspectre/releases/download/v0.1.0/logspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "a5ada1d749c5823fa98a48868afbaf1058dfeeb74d054ed86bc8ef7ef1b52b9e"

      define_method(:install) do
        bin.install "logspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/logspectre/releases/download/v0.1.0/logspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "3f9aa69af1fdf02f4dbcee9855d21396eb2ba7d7b5c113f2b5e32c6161b96d80"

      define_method(:install) do
        bin.install "logspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logspectre/releases/download/v0.1.0/logspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "282110e13a0b5fb433a7b7e77549fb210b51022f232802254fbdeaa2db02b3a8"
      define_method(:install) do
        bin.install "logspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logspectre/releases/download/v0.1.0/logspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "8f6bd3f3fcb63bce13b525789f63f74f0944c6b217f5e6d567bb67f8676c1905"
      define_method(:install) do
        bin.install "logspectre"
      end
    end
  end

  test do
    system "#{bin}/logspectre", "version"
  end
end
