# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logtap < Formula
  desc "Ephemeral log mirror for load testing"
  homepage "https://github.com/ppiankov/logtap"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/logtap/releases/download/v1.8.0/logtap_1.8.0_darwin_amd64.tar.gz"
      sha256 "2d3d2c2bda8f07fafeddacec7e264e911c9b97f8e47d4638c7967455281769df"

      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/logtap/releases/download/v1.8.0/logtap_1.8.0_darwin_arm64.tar.gz"
      sha256 "f2ba8c5cf704bd2be12794de7e5e1796feb84ee7f72f9db6e099c698f3ad4d4e"

      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logtap/releases/download/v1.8.0/logtap_1.8.0_linux_amd64.tar.gz"
      sha256 "85ee1cf9714651ff6c02bc8d5644cffaaccfa9ef8b4cba40fcb4c0aded732017"
      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logtap/releases/download/v1.8.0/logtap_1.8.0_linux_arm64.tar.gz"
      sha256 "a19dc387733bbca32134ba6213d2b7ae1ac9388bf0f41a93cd6865efb0073117"
      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logtap version")
  end
end
