# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logtap < Formula
  desc "Ephemeral log mirror for load testing"
  homepage "https://github.com/ppiankov/logtap"
  version "1.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/logtap/releases/download/v1.9.2/logtap_1.9.2_darwin_amd64.tar.gz"
      sha256 "7a0f3f3c069aaf432355a803b470c54aa23e761ef3411ae34d341467b6aceadd"

      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/logtap/releases/download/v1.9.2/logtap_1.9.2_darwin_arm64.tar.gz"
      sha256 "39979aaa570666bc8d289f334cf2e5ecb6c89c76efe05dee9c1668518fd48ac0"

      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logtap/releases/download/v1.9.2/logtap_1.9.2_linux_amd64.tar.gz"
      sha256 "8b65ef70ce24bcdb25270698528974d9bb59c6e34fa8a6d94b25ce8f0294b4ab"
      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/logtap/releases/download/v1.9.2/logtap_1.9.2_linux_arm64.tar.gz"
      sha256 "be7178a468e0c39ff68d981a51ea0edefc8d06cf9867d91febcb920bd929024e"
      define_method(:install) do
        bin.install "logtap"
        generate_completions_from_executable(bin/"logtap", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logtap version")
  end
end
