# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mongospectre < Formula
  desc "MongoDB collection and index auditor — detects drift between code and live clusters"
  homepage "https://github.com/ppiankov/mongospectre"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.3/mongospectre_0.2.3_darwin_amd64.tar.gz"
      sha256 "eb00a20680d57167918f8944804ecef0b0041a5ade056fe9089f6da365d08e22"

      define_method(:install) do
        bin.install "mongospectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.3/mongospectre_0.2.3_darwin_arm64.tar.gz"
      sha256 "4e29aa7724ce4ff59f1687bedd9adab4783d60cff37cdd668e7e09158bcb5479"

      define_method(:install) do
        bin.install "mongospectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.3/mongospectre_0.2.3_linux_amd64.tar.gz"
      sha256 "674cf138202485783a8b1472d834639bcbd4448eb166cdd99071b8cab6170a11"
      define_method(:install) do
        bin.install "mongospectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.3/mongospectre_0.2.3_linux_arm64.tar.gz"
      sha256 "aac166d0919180ab4076b364eeafe97105b713cfa6929b8fb2a52c430053410e"
      define_method(:install) do
        bin.install "mongospectre"
      end
    end
  end

  test do
    system "#{bin}/mongospectre", "version"
  end
end
