# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mongospectre < Formula
  desc "MongoDB collection and index auditor — detects drift between code and live clusters"
  homepage "https://github.com/ppiankov/mongospectre"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.0/mongospectre_0.2.0_darwin_amd64.tar.gz"
      sha256 "3552995f047bcf5890dbd0e121b784ba71e6a64b0f58fe7add609058475b421c"

      def install
        bin.install "mongospectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.0/mongospectre_0.2.0_darwin_arm64.tar.gz"
      sha256 "97f4b861bf783162b43e2d2139ebb1bb8ec7bc89c92ce85d384c3fa4db554561"

      def install
        bin.install "mongospectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.0/mongospectre_0.2.0_linux_amd64.tar.gz"
      sha256 "395104f2dda8131d2b0bb028390ce325054bf5266761184d996fa43011d273b2"
      def install
        bin.install "mongospectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/mongospectre/releases/download/v0.2.0/mongospectre_0.2.0_linux_arm64.tar.gz"
      sha256 "22afe5796f0db2a0185ea181a6085842f5d0de6be81f101683db638f963a85e3"
      def install
        bin.install "mongospectre"
      end
    end
  end

  test do
    system "#{bin}/mongospectre", "version"
  end
end
