# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neurorouter < Formula
  desc "LLM proxy that cleans, protects, and stabilizes AI sessions before they hit the model"
  homepage "https://neurorouter.dev"
  version "0.1.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.2/neurorouter_0.1.2_darwin_amd64.tar.gz"
      sha256 "9886d0d99c457a0faa09a37fefec70677e4b4cfdbb38b760bee0b61917da57a2"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.2/neurorouter_0.1.2_darwin_arm64.tar.gz"
      sha256 "aa16b698fc5c122dbfa965900b3acce30066700ff401fa1f3cf2a9a062d12076"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.2/neurorouter_0.1.2_linux_amd64.tar.gz"
      sha256 "555fc23521e40d32541ae790af2ab11f8fd69c5177c7c3829d5bbe8215dc2908"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.2/neurorouter_0.1.2_linux_arm64.tar.gz"
      sha256 "cac8129c3c42152504239843e7a02c004ae7e66077b0a5c8fc921437fa2c6573"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
