# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neurorouter < Formula
  desc "LLM proxy that cleans, protects, and stabilizes AI sessions before they hit the model"
  homepage "https://neurorouter.dev"
  version "0.1.3"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.3/neurorouter_0.1.3_darwin_amd64.tar.gz"
      sha256 "01b6ab064e57436382da453a1c067d7ff96db62455414c469dcce058c6b4203e"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.3/neurorouter_0.1.3_darwin_arm64.tar.gz"
      sha256 "542fb185f5bf0b88d8f46bf018c40b22ff996b13fda7542132deb5be8253c1f9"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.3/neurorouter_0.1.3_linux_amd64.tar.gz"
      sha256 "df2c5d9cd97f42114a3eff4edf1938a13b108041ee9e6b09374dd9dd4447c062"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.3/neurorouter_0.1.3_linux_arm64.tar.gz"
      sha256 "068304c883f5d20279bc680ad96b0fa8e62d886ad6aa849d43a349dd1bea5132"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
