# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neurorouter < Formula
  desc "LLM proxy that cleans, protects, and stabilizes AI sessions before they hit the model"
  homepage "https://neurorouter.dev"
  version "0.1.4"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.4/neurorouter_0.1.4_darwin_amd64.tar.gz"
      sha256 "cd3ef19b337e0676e67befec6cd168fb12b1760dfa4edff7fe14d85af3d7f30e"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.4/neurorouter_0.1.4_darwin_arm64.tar.gz"
      sha256 "f9d153ca44f8ef57e5586a32a49dc7aaea89d6f55f7f87bb0ff1dfda6d65f540"

      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.4/neurorouter_0.1.4_linux_amd64.tar.gz"
      sha256 "436b67fa392e258b6b55bdea3331e7f7d72c94517ce3a5f34d5d0907db9ca7d1"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/neurorouter/releases/download/v0.1.4/neurorouter_0.1.4_linux_arm64.tar.gz"
      sha256 "baff27ada676c0d8fa77b9ed081df51abc277bb07f7a895b4c6e0740189e0679"
      define_method(:install) do
        bin.install "neurorouter"
      end
    end
  end

  test do
    system "#{bin}/neurorouter", "version"
  end
end
