# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgpulse < Formula
  desc "PostgreSQL metrics exporter for Prometheus"
  homepage "https://github.com/ppiankov/pgpulse"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.5.0/pgpulse_0.5.0_darwin_amd64.tar.gz"
      sha256 "9622462d21872283d62a46a4200526ba90df07a0109037e3bbc905918b48bd50"

      define_method(:install) do
        bin.install "pgpulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.5.0/pgpulse_0.5.0_darwin_arm64.tar.gz"
      sha256 "b7801c8318acbbf8b08eb702654ac5a7f55086e7e36205398a0bd9388827f318"

      define_method(:install) do
        bin.install "pgpulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.5.0/pgpulse_0.5.0_linux_amd64.tar.gz"
      sha256 "f68e9f436219df787c92b788ec1b0fd35ed25bbce068728839445b67445e0b88"
      define_method(:install) do
        bin.install "pgpulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.5.0/pgpulse_0.5.0_linux_arm64.tar.gz"
      sha256 "54da1de93403e074eb1d62572a87ad1b2e3140a45b88fdfe7de98d81a3831957"
      define_method(:install) do
        bin.install "pgpulse"
      end
    end
  end

  test do
    system "#{bin}/pgpulse", "version"
  end
end
