# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgpulse < Formula
  desc "PostgreSQL metrics exporter for Prometheus"
  homepage "https://github.com/ppiankov/pgpulse"
  version "0.4.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.4.8/pgpulse_0.4.8_darwin_amd64.tar.gz"
      sha256 "2383901e0e018b67121c7687fef7be400aed64bd598ffd3427f5658baeddeb0a"

      define_method(:install) do
        bin.install "pgpulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.4.8/pgpulse_0.4.8_darwin_arm64.tar.gz"
      sha256 "8bef2f258546fc4f203288918541b7bb12af2eccb5af03ac5e87df54a6d841a7"

      define_method(:install) do
        bin.install "pgpulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.4.8/pgpulse_0.4.8_linux_amd64.tar.gz"
      sha256 "ecbe108862d343f1feeeff6d35e7df358edafc0d7668a5dabe3b4c144126d6da"
      define_method(:install) do
        bin.install "pgpulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/pgpulse/releases/download/v0.4.8/pgpulse_0.4.8_linux_arm64.tar.gz"
      sha256 "e561c1b5fb91f359235a2f861a4a6044a77526726ddcd2c4adb9ce1e7bcce0bd"
      define_method(:install) do
        bin.install "pgpulse"
      end
    end
  end

  test do
    system "#{bin}/pgpulse", "version"
  end
end
