# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdsspectre < Formula
  desc "Database instance waste auditor — finds idle, oversized, and misconfigured instances in AWS RDS and GCP Cloud SQL"
  homepage "https://github.com/ppiankov/rdsspectre"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.3/rdsspectre_0.1.3_darwin_amd64.tar.gz"
      sha256 "f635de23ee4e6d4368efee52487110ef28c726e3dab09c27eef25f3cdc6153d8"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.3/rdsspectre_0.1.3_darwin_arm64.tar.gz"
      sha256 "c51acb7d47ec14356a0fc51557333304499d0ff5205c71249397c473d7e7f732"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.3/rdsspectre_0.1.3_linux_amd64.tar.gz"
      sha256 "cdb86424ee784e0e4acccc6f77ea375ab5b1eab5e058c52518d7176a0ff41812"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.3/rdsspectre_0.1.3_linux_arm64.tar.gz"
      sha256 "1c0b390f33acb91546c966044873ad19aaced39c41635fe27620a6b720391d23"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  test do
    system "#{bin}/rdsspectre", "version"
  end
end
