# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdsspectre < Formula
  desc "Database instance waste auditor — finds idle, oversized, and misconfigured instances in AWS RDS and GCP Cloud SQL"
  homepage "https://github.com/ppiankov/rdsspectre"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.2/rdsspectre_0.1.2_darwin_amd64.tar.gz"
      sha256 "3e1f1922f980ee1de7d4472a616e8f6bdf7cabecdc165cc5d8df0e527ac7c1e9"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.2/rdsspectre_0.1.2_darwin_arm64.tar.gz"
      sha256 "f1019436f4544fd106563346a62d22263069c324ae75d47e4dc29c4652a963a1"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.2/rdsspectre_0.1.2_linux_amd64.tar.gz"
      sha256 "994c333d02caaae5c83a1906ee28806e3cc13a304e7a8dc5bb6651341bec58af"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.2/rdsspectre_0.1.2_linux_arm64.tar.gz"
      sha256 "04ae6c960d1a2ad196629a69b28fc106feaab858bec86f6e3d5f455c7990c1a9"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  test do
    system "#{bin}/rdsspectre", "version"
  end
end
