# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdsspectre < Formula
  desc "Database instance waste auditor — finds idle, oversized, and misconfigured instances in AWS RDS and GCP Cloud SQL"
  homepage "https://github.com/ppiankov/rdsspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.0/rdsspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "7aada44f767f7945e386d9331bbf31156441361da14636ee84c6e7f41e6021c6"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.0/rdsspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "ac4abf43f12ffc55bdcd102876e4d7667f148f118f0b2f7b93e1bb0226b218da"

      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.0/rdsspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "71114944d749d5786d4802382c4f936fdf1d38c5356cf7fa718072e61e2adf52"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/rdsspectre/releases/download/v0.1.0/rdsspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "2a10afc151e073254e09f44cbe0eb1e1cbe3e3f8bdd8a56abc2ff0ccc67defff"
      define_method(:install) do
        bin.install "rdsspectre"
      end
    end
  end

  test do
    system "#{bin}/rdsspectre", "version"
  end
end
