# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redisspectre < Formula
  desc "Redis waste and hygiene auditor"
  homepage "https://github.com/ppiankov/redisspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/redisspectre/releases/download/v0.1.0/redisspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "eb610790ee68cd4d571095fbe956d11602176f817b7bf17d31f337b263888afe"

      define_method(:install) do
        bin.install "redisspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/redisspectre/releases/download/v0.1.0/redisspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "8ffc97252dab637700463f3ddfe19741a4f26063a87a04b0ae41a44acc86c189"

      define_method(:install) do
        bin.install "redisspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/redisspectre/releases/download/v0.1.0/redisspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "5f62d943f7478359adcf3c67c9ca0e9b99afd60b25b967223d4460eb9fd5f905"
      define_method(:install) do
        bin.install "redisspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/redisspectre/releases/download/v0.1.0/redisspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "f2b8589176af1897b7898dd17b40e82964fa6259c69a5f1f920cf7c1525dd485"
      define_method(:install) do
        bin.install "redisspectre"
      end
    end
  end

  test do
    system "#{bin}/redisspectre", "version"
  end
end
