# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runforge < Formula
  desc "Dependency-aware parallel task runner for AI coding agents"
  homepage "https://github.com/ppiankov/runforge"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/runforge/releases/download/v0.10.0/runforge_0.10.0_darwin_amd64.tar.gz"
      sha256 "ba5842e2429ee8d12928d78ee857f3f47b4fb1f2c94340faf57ef529e34e7edc"

      define_method(:install) do
        bin.install "runforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/runforge/releases/download/v0.10.0/runforge_0.10.0_darwin_arm64.tar.gz"
      sha256 "8420de6c227f723b1658b99ed6ed039b0984c226a8bef6378a21db27d523bdbd"

      define_method(:install) do
        bin.install "runforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/runforge/releases/download/v0.10.0/runforge_0.10.0_linux_amd64.tar.gz"
      sha256 "d210caab623fa3e63a8df17b6f73f4f3fc85c50f3a507294eb6c1b0602c1b32d"
      define_method(:install) do
        bin.install "runforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/runforge/releases/download/v0.10.0/runforge_0.10.0_linux_arm64.tar.gz"
      sha256 "2056011a8c7ba9b2a1fd2d0f58cf6fe256f0c60ce08287ee25040b713e08ee61"
      define_method(:install) do
        bin.install "runforge"
      end
    end
  end

  test do
    system "#{bin}/runforge", "version"
  end
end
