# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3spectre < Formula
  desc "AWS S3 bucket usage auditor — detects drift between code and live infrastructure"
  homepage "https://github.com/ppiankov/s3spectre"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.3/s3spectre_0.6.3_darwin_amd64.tar.gz"
      sha256 "c4210e287cff0cce1d7cf13e0dd28b22c1ec4a58b2b8216a16e21e1fcfa4b43a"

      define_method(:install) do
        bin.install "s3spectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.3/s3spectre_0.6.3_darwin_arm64.tar.gz"
      sha256 "aad948bdb8a52e4ded8b0eee312d526f3c5c1aac888fbd94a3674938811b9cf8"

      define_method(:install) do
        bin.install "s3spectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.3/s3spectre_0.6.3_linux_amd64.tar.gz"
      sha256 "d3102f0b86dab1e73b3c060360545f1fe65ade09cc91deea75b2da6cf752c967"
      define_method(:install) do
        bin.install "s3spectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.3/s3spectre_0.6.3_linux_arm64.tar.gz"
      sha256 "ac9f260cbe2a9c3e4446bc0c69af79634bd5d3ae2f58aadcb77a99d7802f631f"
      define_method(:install) do
        bin.install "s3spectre"
      end
    end
  end

  test do
    system "#{bin}/s3spectre", "version"
  end
end
