# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3spectre < Formula
  desc "AWS S3 bucket usage auditor — detects drift between code and live infrastructure"
  homepage "https://github.com/ppiankov/s3spectre"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.1/s3spectre_0.6.1_darwin_amd64.tar.gz"
      sha256 "919055c9bf6269c25d2641e50c52ab521022a9cbee0a50d3587f7bddd14c4041"

      define_method(:install) do
        bin.install "s3spectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.1/s3spectre_0.6.1_darwin_arm64.tar.gz"
      sha256 "5bdf98dec27fb9ec9e9c0bd5355689a7930fc45e686bf9c572a1644eb69b0383"

      define_method(:install) do
        bin.install "s3spectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.1/s3spectre_0.6.1_linux_amd64.tar.gz"
      sha256 "fc314b1a6952ef4a6c6921d38069a9736bdbde9d59348b74d81ce5f122dd6084"
      define_method(:install) do
        bin.install "s3spectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/s3spectre/releases/download/v0.6.1/s3spectre_0.6.1_linux_arm64.tar.gz"
      sha256 "dae923acd0e842c12725b619a46ed268234fc0c38cd5e20daf605e1286c61125"
      define_method(:install) do
        bin.install "s3spectre"
      end
    end
  end

  test do
    system "#{bin}/s3spectre", "version"
  end
end
