# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snowspectre < Formula
  desc "Snowflake waste and hygiene auditor"
  homepage "https://github.com/ppiankov/snowspectre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/snowspectre/releases/download/v0.1.0/snowspectre_0.1.0_darwin_amd64.tar.gz"
      sha256 "ef4aedf6e5da0e4eb760490f0b141c380262e91e5c4ede03a857a51189220d7d"

      define_method(:install) do
        bin.install "snowspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/snowspectre/releases/download/v0.1.0/snowspectre_0.1.0_darwin_arm64.tar.gz"
      sha256 "730dc645277802e2a1feb2239e642d517a06c342bade6bc2644903d81a19deaa"

      define_method(:install) do
        bin.install "snowspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/snowspectre/releases/download/v0.1.0/snowspectre_0.1.0_linux_amd64.tar.gz"
      sha256 "42b08a255cab719d0f44104c6f5f7d1fe0171b676db7a3271f4c77284baa6fda"
      define_method(:install) do
        bin.install "snowspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/snowspectre/releases/download/v0.1.0/snowspectre_0.1.0_linux_arm64.tar.gz"
      sha256 "2f73316f4710cdc5699ccdfdbc749960016a9bd4f1d35c63499989b74e18d820"
      define_method(:install) do
        bin.install "snowspectre"
      end
    end
  end

  test do
    system "#{bin}/snowspectre", "version"
  end
end
