# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokencontrol < Formula
  desc "Dependency-aware parallel task runner for AI coding agents"
  homepage "https://github.com/ppiankov/tokencontrol"
  version "0.26.5"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.26.5/tokencontrol_0.26.5_darwin_amd64.tar.gz"
      sha256 "d273752803a282ee20c1764f6bcbb1a6db44b3385086d7b17308b38062d579f5"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.26.5/tokencontrol_0.26.5_darwin_arm64.tar.gz"
      sha256 "6e9768ea818feebee4f5f44248f1a81cc147dd03ee69883e7dce8f50ff5ae6af"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.26.5/tokencontrol_0.26.5_linux_amd64.tar.gz"
      sha256 "a678044e271a5dbe47935780e4bd3f725e456a1af507949bb0f1d6d4749cd4ad"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.26.5/tokencontrol_0.26.5_linux_arm64.tar.gz"
      sha256 "f28e1307333ad4143d0e809aad6654cfc4d5b60e82339d3bbd5bfc433c16f5dc"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  test do
    system "#{bin}/tokencontrol", "version"
  end
end
