# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokencontrol < Formula
  desc "Dependency-aware parallel task runner for AI coding agents"
  homepage "https://github.com/ppiankov/tokencontrol"
  version "0.23.2"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.23.2/tokencontrol_0.23.2_darwin_amd64.tar.gz"
      sha256 "9374cbb02c0d2f19cf18e1b84e1e00e84d06ee5d8df2fe0ffdf19ae3ae6fa5a3"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.23.2/tokencontrol_0.23.2_darwin_arm64.tar.gz"
      sha256 "5baddeb78084fffb052e1ceb71efcebf3e14b6b44a33f28c6948e195677fdfaf"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.23.2/tokencontrol_0.23.2_linux_amd64.tar.gz"
      sha256 "7f26dff296c63f7eb5eba2beeff35d1312de361680858d9ef60cf6b96e417a53"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.23.2/tokencontrol_0.23.2_linux_arm64.tar.gz"
      sha256 "8746b063662f516a6d2f89bd80f086500b37103aefb1b6d8ac80ce5afe5efc1c"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  test do
    system "#{bin}/tokencontrol", "version"
  end
end
