# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokencontrol < Formula
  desc "Dependency-aware parallel task runner for AI coding agents"
  homepage "https://github.com/ppiankov/tokencontrol"
  version "0.27.0"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.27.0/tokencontrol_0.27.0_darwin_amd64.tar.gz"
      sha256 "7400442eded686af562076b467abec73ae2010b86482781f7e80aab2a5799e61"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.27.0/tokencontrol_0.27.0_darwin_arm64.tar.gz"
      sha256 "9772d876593c9c202f27fc793a8a2c1f7a2fd8d79af65537947d5b91255d60bc"

      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.27.0/tokencontrol_0.27.0_linux_amd64.tar.gz"
      sha256 "32940e5ea324078a0636f8588ee78823dba22434837fc601e9b60f40606f0648"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/tokencontrol/releases/download/v0.27.0/tokencontrol_0.27.0_linux_arm64.tar.gz"
      sha256 "8c045ce46fd0b09d3256d3a20ee5b1eb475254c5ecc0154d2a75605431565a11"
      define_method(:install) do
        bin.install "tokencontrol"
      end
    end
  end

  test do
    system "#{bin}/tokencontrol", "version"
  end
end
