# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultspectre < Formula
  desc "Vault secret usage auditor - find missing, unused, and stale secrets"
  homepage "https://github.com/ppiankov/vaultspectre"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.6.0/vaultspectre_0.6.0_darwin_amd64.tar.gz"
      sha256 "3339a1638377301da51e3d3f0b2fc5896aaabe6ac1e7387548f1e2f7acffe3df"

      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.6.0/vaultspectre_0.6.0_darwin_arm64.tar.gz"
      sha256 "4f4f8c856a385f5e7cfae6722d39435ac8d5aab98efb2116b24524bfda177635"

      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.6.0/vaultspectre_0.6.0_linux_amd64.tar.gz"
      sha256 "a5ed6e4434680a8527bd6a03994a83834b8a97958bf97be60428ea19c2b6a533"
      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.6.0/vaultspectre_0.6.0_linux_arm64.tar.gz"
      sha256 "c8215e9747d1438a76942d66592f5149a4524a9789803757556b25c84eaf7d1c"
      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
  end

  test do
    system "#{bin}/vaultspectre", "version"
  end
end
