# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultspectre < Formula
  desc "Vault secret usage auditor - find missing, unused, and stale secrets"
  homepage "https://github.com/ppiankov/vaultspectre"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.5.1/vaultspectre_0.5.1_darwin_amd64.tar.gz"
      sha256 "b9ae411a9b29866016d9d67d69dd9bac97560315c6cd4ebdb0ebb3f6ec979b2a"

      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.5.1/vaultspectre_0.5.1_darwin_arm64.tar.gz"
      sha256 "e255b6b5b1236a8b4a9050290a7575d0c6f87963187d4339f1cec4850f887dd9"

      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.5.1/vaultspectre_0.5.1_linux_amd64.tar.gz"
      sha256 "ecea8e8c1d13941e24828d6a4162d7df66bfbd930e50438e789d1d770b1aea35"
      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vaultspectre/releases/download/v0.5.1/vaultspectre_0.5.1_linux_arm64.tar.gz"
      sha256 "889cc014a31bdc3e3136ec7a5e90a35f765ceb6a3fd9fa8540b14b15d5794e0e"
      define_method(:install) do
        bin.install "vaultspectre"
      end
    end
  end

  test do
    system "#{bin}/vaultspectre", "version"
  end
end
