# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vectorpad < Formula
  desc "Pre-flight staging area for reasoning intent"
  homepage "https://github.com/ppiankov/vectorpad"
  version "0.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.20.0/vectorpad_0.20.0_darwin_amd64.tar.gz"
      sha256 "3217be3616c43a294fccbf61982532f91ae0eca0e033eefedbed4fc174c37519"

      define_method(:install) do
        bin.install "vectorpad"
        bin.install "vp"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.20.0/vectorpad_0.20.0_darwin_arm64.tar.gz"
      sha256 "defb3a16f3f44497aac47871ff27e3e05c24118850dae44b80654c2c6decb11d"

      define_method(:install) do
        bin.install "vectorpad"
        bin.install "vp"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.20.0/vectorpad_0.20.0_linux_amd64.tar.gz"
      sha256 "cd208d8e1bd4acbdf9ff0329042eefe3c5d8f9c7e45d8bf828651cd47e1d030a"
      define_method(:install) do
        bin.install "vectorpad"
        bin.install "vp"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.20.0/vectorpad_0.20.0_linux_arm64.tar.gz"
      sha256 "e03bed689a5a8bae88725d8a6588f7ed2689de03392c75a7fc6d0e172d7478e3"
      define_method(:install) do
        bin.install "vectorpad"
        bin.install "vp"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vectorpad version")
  end
end
