# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vectorpad < Formula
  desc "Pre-flight staging area for reasoning intent"
  homepage "https://github.com/ppiankov/vectorpad"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.15.0/vectorpad_0.15.0_darwin_amd64.tar.gz"
      sha256 "4786f8ca200588406189e06d6cf9f97787458e30555f65201e291693aa488fce"

      define_method(:install) do
        bin.install "vectorpad"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.15.0/vectorpad_0.15.0_darwin_arm64.tar.gz"
      sha256 "9c5760b76401b9b8b258d74559f72fdd64f0e37fa809770ad21d679ad16d2ba8"

      define_method(:install) do
        bin.install "vectorpad"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.15.0/vectorpad_0.15.0_linux_amd64.tar.gz"
      sha256 "547817289a5f285803ec08c88c7671d2d0b833af5b519d132e9b6283c838be23"
      define_method(:install) do
        bin.install "vectorpad"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/vectorpad/releases/download/v0.15.0/vectorpad_0.15.0_linux_arm64.tar.gz"
      sha256 "56cc18189167b15416853cd159c3e131823b81ebe7fb404361c2ff0903e00b83"
      define_method(:install) do
        bin.install "vectorpad"
        generate_completions_from_executable(bin/"vectorpad", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vectorpad version")
  end
end
