# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wocontrol < Formula
  desc "WO spec crawler and execution pipeline"
  homepage "https://github.com/ppiankov/wocontrol"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.4.0/wocontrol_0.4.0_darwin_amd64.tar.gz"
      sha256 "094e62ffb124dac1631a780d211aeba9bcb03f202b20319b8f8c92398f940716"

      define_method(:install) do
        bin.install "wocontrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.4.0/wocontrol_0.4.0_darwin_arm64.tar.gz"
      sha256 "f9b1e94cd9f1ec4f902158447045e2429acaba6f1ebf6645dc33f88503f1900d"

      define_method(:install) do
        bin.install "wocontrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.4.0/wocontrol_0.4.0_linux_amd64.tar.gz"
      sha256 "46279c09b76c252f80e1baf562f0758b848a1b7cf26e3fb63121db15738a415c"
      define_method(:install) do
        bin.install "wocontrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.4.0/wocontrol_0.4.0_linux_arm64.tar.gz"
      sha256 "d7a8e0ac4a0651a57eaeac39fade720225dcf6a4fb93ba566bda8d08636606db"
      define_method(:install) do
        bin.install "wocontrol"
      end
    end
  end

  test do
    system "#{bin}/wocontrol", "version"
  end
end
