# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wocontrol < Formula
  desc "WO spec crawler and execution pipeline"
  homepage "https://github.com/ppiankov/wocontrol"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.3.0/wocontrol_0.3.0_darwin_amd64.tar.gz"
      sha256 "57cfd73eb6d23ab2a9a04032dea360f8563d2bcd148c6e3006e2c5317e3206b6"

      define_method(:install) do
        bin.install "wocontrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.3.0/wocontrol_0.3.0_darwin_arm64.tar.gz"
      sha256 "d1e4e08e76003e13e5e30a6f6e10e3f9f6124fc8ee888b1502b67d26cb1f53c1"

      define_method(:install) do
        bin.install "wocontrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.3.0/wocontrol_0.3.0_linux_amd64.tar.gz"
      sha256 "164e6aa64a86fc7b8bb70b4172334a174d3beaa4f3f08233945e9d2c7026ad0f"
      define_method(:install) do
        bin.install "wocontrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppiankov/wocontrol/releases/download/v0.3.0/wocontrol_0.3.0_linux_arm64.tar.gz"
      sha256 "2af901e6631772911534199a4201b7e5130efdd34dd215ee941a4e0d27547ae4"
      define_method(:install) do
        bin.install "wocontrol"
      end
    end
  end

  test do
    system "#{bin}/wocontrol", "version"
  end
end
